import { Product } from "@/types/product";

export const products: Product[] = [
  {
    slug: "anti-falten-schlaf-bh",
    name: "Anti-Falten Schlaf BH",
    shortName: "Schlaf BH",
    price: 49.5,
    originalPrice: 69.9,
    currency: "EUR",
    description:
      "Der Original Anti-Falten Schlaf BH: Er hält dein Dekolleté nachts sanft in Position — damit du morgens ohne frische Schlaffalten aufwachst.",
    longDescription:
      "Der MELYLA Anti-Falten Schlaf BH hält dein Dekolleté während des Schlafs sanft zusammen und verhindert so das Entstehen neuer Falten. Aus besonders weichem, atmungsaktivem Material gefertigt, trägt er sich so bequem, dass du ihn kaum spürst. Entwickelt in Deutschland für Frauen, die auch im Schlaf aktiv für ihre Haut tun möchten.",
    benefits: [
      "Reduziert bestehende Dekolleté-Falten",
      "Verhindert neue Schlaffalten",
      "Sofort spürbare Straffung",
      "Atmungsaktives Material",
      "Kein BPA, hautfreundlich zertifiziert",
    ],
    materials: "95% Baumwolle, 5% Elasthan — OEKO-TEX® zertifiziert",
    care: "Handwäsche oder Schonprogramm 30°C, nicht in den Trockner",
    imageSrc: "/images/products/bh-produkt-1.jpeg",
    images: [
      "/images/products/bh-produkt-1.jpeg",
      "/images/products/bh-produkt-2.jpeg",
      "/images/products/bh-produkt-3.jpeg",
      "/images/products/bh-cream-frontal.webp",
      "/images/products/bh-seitlich-model.jpg",
      "/images/products/bh-cream-plussize.jpeg",
      "/images/products/bh-nude-seite.jpg",
      "/images/products/bh-nude-ruecken.jpg",
      "/images/products/bh-detail-schulter.jpg",
      "/images/products/bh-detail-verschluss.jpg",
      "/images/products/bh-detail-racerback.jpg",
    ],
    category: "bh",
    rating: 4.79,
    reviewCount: 52,
    isBestseller: true,
    sizes: ["S (60–70 cm)", "M (70–80 cm)", "L (80–90 cm)", "XL (90–100 cm)"],
  },
  {
    slug: "anti-falten-kissen",
    name: "Anti-Falten Kissen",
    shortName: "Schlafkissen",
    price: 49.5,
    currency: "EUR",
    description:
      "Das ergonomische Anti-Falten Kissen — schläfst du in der optimalen Position für jugendliche Haut.",
    longDescription:
      "Das MELYLA Anti-Falten Kissen unterstützt deinen Kopf und Nacken in einer Position, die Druckfalten minimiert. Die spezielle Kontur hält Gesicht und Dekolleté frei vom Kissendruck — für eine Haut, die morgens ausgeruht statt zerdrückt aussieht.",
    benefits: [
      "Ergonomische Anti-Falten-Form",
      "Reduziert Druckfalten im Gesicht",
      "Unterstützt Nacken und Wirbelsäule",
      "Hypoallergener Memory-Foam-Kern",
      "Waschbarer Kissenbezug inklusive",
    ],
    materials: "Memory-Foam-Kern, Kissenbezug aus 100% Bio-Baumwolle",
    care: "Bezug bei 60°C waschbar, Kern lufttrocknen",
    imageSrc: "/images/products/MELYLA_Kissen_Weiss-Satin_HeroShot_Produkt-auf-Bett_16x9.jpeg",
    images: [
      "/images/products/MELYLA_Kissen_Weiss-Satin_HeroShot_Produkt-auf-Bett_16x9.jpeg",
      "/images/products/MELYLA_Kissen_Grau_HeroShot_Marmor-Lavendel-Props_v1_16x9.jpeg",
      "/images/products/MELYLA_Kissen_Grau_HeroShot_Wand-Morgenlicht-artistisch_16x9.jpeg",
      "/images/products/MELYLA_Kissen_Grau_Lifestyle_Schlafzimmer-Totale_16x9.jpeg",
      "/images/products/MELYLA_Kissen_Grau_Nutzungsshot_Frau-Rueckenschlaeferin-Bett_16x9.jpeg",
      "/images/products/MELYLA_Kissen_Weiss-Satin_Detailshot_Hand-beruehrt-Stoff_16x9.jpeg",
      "/images/products/MELYLA_Kissen_Weiss-Satin_Detailshot_Label-Nahaufnahme_16x9.jpeg",
      "/images/products/MELYLA_Kissen_Weiss-Satin_Nutzungsshot_Frau-Rueckenschlaeferin-Holz-Bett_16x9.jpeg",
      "/images/products/MELYLA_Kissen_Weiss-Satin_Nutzungsshot_Frau-Seitenschlaeferin-Bett_16x9.jpeg",
    ],
    category: "kissen",
    rating: 4.74,
    reviewCount: 23,
    isBestseller: true,
  },
  {
    slug: "anti-falten-schlafmaske",
    name: "Anti-Falten Schlafmaske",
    shortName: "Schlafmaske",
    price: 10.0,
    originalPrice: 12.0,
    currency: "EUR",
    description: "Sanfte Augenmaske für erholsamen Tiefschlaf ohne Druckstellen.",
    longDescription:
      "Die MELYLA Schlafmaske blockiert Licht vollständig, ohne dabei Druck auf die empfindliche Augenpartie auszuüben. Ihre weiche Wölbung schützt die Haut vor Faltenbildung durch Kissendruck.",
    benefits: [
      "Vollständige Lichtblockade",
      "Kein Druck auf Augenlider",
      "Verhindert Augenfalten",
      "Ultraleicht und atmungsaktiv",
    ],
    materials: "Seide außen, weiches Schaumstoff-Futter",
    care: "Handwäsche 30°C",
    imageSrc: "/images/products/MELYLA_Schlafmaske_Nutzungsshot_Model1.jpeg",
    images: [
      "/images/products/MELYLA_Schlafmaske_HeroShot.jpg",
      "/images/products/MELYLA_Schlafmaske_Lifestyle_Bett.jpeg",
      "/images/products/MELYLA_Schlafmaske_Nutzungsshot_Model1.jpeg",
      "/images/products/MELYLA_Schlafmaske_Nutzungsshot_Model2.jpeg",
    ],
    category: "accessoires",
    rating: 5.0,
    reviewCount: 1,
    isSale: true,
  },
  {
    slug: "haar-gummie",
    name: "Scrunchie / Haargummi 4er-Pack",
    shortName: "Scrunchie",
    price: 4.40,
    originalPrice: 5.50,
    currency: "EUR",
    description: "Luxuriöses Haargummi mit seidenweicher Eleganz — stilvolles Design trifft herausragende Haargesundheit.",
    longDescription: "Der MELYLA Scrunchie vereint seidenweiche Eleganz mit schonender Haargesundheit. Das besondere Material schützt dein Haar vor Bruch und Frizz — für strahlend glänzendes Haar, das gepflegt aussieht.",
    benefits: [
      "Schützt vor Haarbruch und Frizz",
      "Sanfte Pflege für strahlendes Haar",
      "Seidenweiche Haptik",
      "4er-Pack — ein Set für jeden Look",
      "Circa 5,5 cm Größe",
    ],
    materials: "88% Polyester, 12% Elasthan",
    care: "Handwäsche 30°C",
    imageSrc: "/images/products/MELYLA_Haarband_HeroShot_Mehrere.jpeg",
    images: [
      "/images/products/MELYLA_Haarband_HeroShot_Mehrere.jpeg",
      "/images/products/MELYLA_Haarband_Detailshot.jpeg",
      "/images/products/MELYLA_Haarband_Nutzungsshot_Frau.jpeg",
    ],
    category: "accessoires",
    rating: 5.0,
    reviewCount: 1,
    isSale: true,
  },
  {
    slug: "schwamm",
    name: "ECO Reinigungsschwamm",
    shortName: "Reinigungsschwamm",
    price: 14.40,
    originalPrice: 18.00,
    currency: "EUR",
    description: "Nachhaltiger, wiederverwendbarer Reinigungsschwamm für die tägliche Gesichtspflege — sanft, hautfreundlich und umweltbewusst.",
    longDescription: "Der MELYLA ECO Reinigungsschwamm ist die nachhaltige Alternative zu Einweg-Wattepads. Aus Mikrofaser und Baumwolle gefertigt, entfernt er Make-up und Unreinheiten besonders schonend — auch für empfindliche Haut.",
    benefits: [
      "Hautfreundlich für empfindliche Haut",
      "Nachhaltig & wiederverwendbar",
      "Schonende Make-up-Entfernung",
      "Mikrofaser & Baumwolle, 11,5 x 1 cm",
      "Langlebig bei richtiger Pflege",
    ],
    materials: "Mikrofaser-Schwamm und Baumwolle",
    care: "Hand- oder Maschinenwäsche in warmem Wasser, an der Luft trocknen",
    imageSrc: "/images/products/MELYLA_Schwamm_HeroShot.jpeg",
    images: [
      "/images/products/MELYLA_Schwamm_HeroShot.jpeg",
      "/images/products/MELYLA_Schwamm_Lifestyle_1.jpeg",
      "/images/products/MELYLA_Schwamm_Lifestyle_2.jpeg",
      "/images/products/MELYLA_Schwamm_Nutzungsshot_Model.jpeg",
    ],
    category: "accessoires",
    rating: 5.0,
    reviewCount: 1,
    isSale: true,
  },
  {
    slug: "eco-abschminkpads",
    name: "ECO Abschminkpads 10er-Pack",
    shortName: "Abschminkpads",
    price: 6.8,
    originalPrice: 8.5,
    currency: "EUR",
    description: "Wiederverwendbare Abschminkpads aus Bio-Baumwolle — nachhaltig und sanft.",
    longDescription:
      "Die MELYLA ECO Abschminkpads sind die nachhaltige Alternative zu Einweg-Wattepads. Aus Bio-Baumwolle gefertigt, sind sie weich genug für empfindliche Haut und nach dem Waschen immer wieder verwendbar.",
    benefits: [
      "100% wiederverwendbar",
      "Bio-Baumwolle, hautfreundlich",
      "Ersetzt bis zu 1.000 Einweg-Pads",
      "Mit Wäschenetz im Lieferumfang",
    ],
    materials: "100% Bio-Baumwolle, GOTS-zertifiziert",
    care: "Bis 60°C maschinenwaschbar",
    imageSrc: "/images/products/MELYLA_Abschminkpad_HeroShot_1.jpeg",
    images: [
      "/images/products/MELYLA_Abschminkpad_HeroShot_1.jpeg",
      "/images/products/MELYLA_Abschminkpad_HeroShot_2.jpeg",
      "/images/products/MELYLA_Abschminkpad_Detailshot_1.jpeg",
      "/images/products/MELYLA_Abschminkpad_Detailshot_2.jpeg",
      "/images/products/MELYLA_Abschminkpad_Lifestyle_1.jpeg",
      "/images/products/MELYLA_Abschminkpad_Lifestyle_2.jpeg",
    ],
    category: "accessoires",
    rating: 5.0,
    reviewCount: 1,
    isSale: true,
    isNew: false,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getBestsellers(): Product[] {
  return products.filter((p) => p.isBestseller);
}

export function getRelatedProducts(currentSlug: string, limit = 3): Product[] {
  return products.filter((p) => p.slug !== currentSlug).slice(0, limit);
}
